version: "3"

services:
  frontend-container:
    build: .
    networks:
      - default-network
    ports:
      - "8888:80"

  backend-container:
    build: ./../business-loan-backend
    networks:
      - default-network

networks:
  default-network:
